# FOR OFFLINE DEVELOPMENT

version: "3.7"

services:
  db:
    image: mysql
    env_file: 
      - .env
    ports: 
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
volumes:
  mysql_db:
