version: "3"

services:
  app:
    build: .
    depends_on:
      - db
    env_file: 
      - .env
    ports: 
      - 8089:8089
  db:
    image: mysql
    env_file: 
      - .env
    ports: 
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
volumes:
  mysql_db:
